### ISSUE TITLE
Invoke in java

### ISSUE THREAD

**Issue by LouisGJBertrand** [PYLOTT/studio.louisbertrand.autorestart#1]
One triggering /autorestart <param>
this error occurs

```log
[20:44:01] [Server thread/INFO]: FR_Pylott issued server command: /autorestart
[20:44:01] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'autorestart' in plugin AutoRestartForSpigot v1.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-133]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-133]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-133]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[patched_1.15.2.jar:git-Paper-133]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[patched_1.15.2.jar:git-Paper-133]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-133]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-133]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-133]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-133]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-133]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-133]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-133]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-133]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-133]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-133]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1102) ~[patched_1.15.2.jar:git-Paper-133]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-133]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at java.lang.reflect.Method.invoke(Method.java:559) ~[?:?]
	at studio.louisbertrand.autorestart.defaultCommandParser.parse(defaultCommandParser.java:95) ~[?:?]
	at studio.louisbertrand.autorestart.Main.onCommand(Main.java:76) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-133]
	... 17 more
```

seem to occur because of lines between 92 and 96 of class defaultCommandParser

17/03/2020 at 9:06pm

**Comment by LouisGJBertrand** [comment]
Fixed and explained in next commit in file defaultCommandParser

**Comment by LouisGJBertrand** [comment]
The goal was to put 'this' at 'object' argument in invoke method, this avoid any errors like Null or NullPointer caused by this last method.

**Comment by LouisGJBertrand** [comment]
it should be
```java
// Actual invoking
final Method method = defaultCommandParser.class.getDeclaredMethod(methodName , argumentsTypes);
// NOTE:   use 'this' to say who is triggering (Grooble)
final commandResponse response = (commandResponse) method.invoke(this, arguments);
```
